name: gh-seconnd-npm-project
on: push
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Depedencies
        run: npm ci
      - name: Run Tests
        run: npm test
  Deploy:
    needs: Test
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v7
      - name: Install NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: "24"
      - name: Install Depedencies
        run: npm ci
      - name: Build project
        run: npm run build
      - name: Deploy App
        run: echo "Deploy app ..."